# Generated by Django 4.0.3 on 2022-03-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='token',
            field=models.TextField(default='', verbose_name='Register token'),
            preserve_default=False,
        ),
    ]
