# Generated by Django 4.0.3 on 2022-03-23 20:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
        ('tracks', '0001_initial'),
        ('genres', '0001_initial'),
        ('playlists', '0001_initial'),
        ('artists', '0001_initial'),
        ('authentication', '0002_customuser_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Активирован'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_admin',
            field=models.BooleanField(default=False, verbose_name='Администратор'),
        ),
        migrations.CreateModel(
            name='UserFavorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('albums', models.ManyToManyField(related_name='favorite_albums', to='albums.album')),
                ('artists', models.ManyToManyField(related_name='favorite_artists', to='artists.artist')),
                ('genres', models.ManyToManyField(related_name='favorite_genres', to='genres.genre')),
                ('playlists', models.ManyToManyField(related_name='favorite_playlists', to='playlists.playlist')),
                ('tracks', models.ManyToManyField(related_name='favorite_tracks', to='tracks.track')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранное',
                'verbose_name_plural': 'Избранное',
            },
        ),
    ]
