# Generated by Django 4.0.3 on 2022-03-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название плейлиста')),
                ('description', models.TextField(verbose_name='Описание плейлиста')),
                ('photo', models.ImageField(upload_to='images/playlists_covers', verbose_name='Обложка')),
                ('track', models.ManyToManyField(related_name='playlist', to='tracks.track', verbose_name='Треки')),
            ],
            options={
                'verbose_name': 'Плейлист',
                'verbose_name_plural': 'Плейлист',
            },
        ),
    ]
