# Generated by Django 4.0.3 on 2022-04-03 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0001_initial'),
        ('playlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Отображается?'),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='track',
            field=models.ManyToManyField(blank=True, related_name='playlist', to='tracks.track', verbose_name='Треки'),
        ),
    ]
