# Generated by Django 4.0.3 on 2022-03-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(blank=True, max_length=255, verbose_name='Псевдоним')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя исполнителя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия исполнителя')),
                ('date_of_birth', models.DateField(verbose_name='Дата рождения')),
                ('photo', models.ImageField(upload_to='images/artists_photos', verbose_name='Фото')),
                ('about', models.TextField(verbose_name='Об исполнителе')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
    ]
