# Generated by Django 4.0.3 on 2022-03-23 20:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0001_initial'),
        ('tracks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Название альбома')),
                ('date_of_release', models.DateField(default=django.utils.timezone.now, verbose_name='Дата выпуска')),
                ('description', models.TextField(verbose_name='Описание альбома')),
                ('cover', models.ImageField(upload_to='images/albums_covers', verbose_name='Обложка')),
                ('type_of_album', models.CharField(choices=[('Сингл', 'Сингл'), ('EP', 'EP'), ('Альбом', 'Альбом')], default='Альбом', max_length=6, verbose_name='Тип альбома')),
                ('artists', models.ManyToManyField(related_name='albums', to='artists.artist', verbose_name='Исполнители')),
                ('track', models.ManyToManyField(related_name='album', to='tracks.track', verbose_name='Треки')),
            ],
            options={
                'verbose_name': 'Альбом',
                'verbose_name_plural': 'Альбомы',
            },
        ),
    ]
